services:
  strapi:
    image: strapi/strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: /app/data/data.db
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      URL: https://strapi-cms.schrum.xyz
      HOST: 0.0.0.0
      PORT: 1337
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./public/uploads:/app/public/uploads
      - ./data:/app/data

    labels:
      - "coolify.url=https://strapi-cms.schrum.xyz"
      - "coolify.enable=true"
