services:
  strapi:
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: production
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./public/uploads:/app/public/uploads
      - ./data:/app/data # Assuming SQLite database will be stored in ./data director
    ports:
      - "1337:1337"

volumes:
  strapi-data:
